version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres

    ports:
      - '5432:5432'

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
  
  api:
    build:
      context: ./
      dockerfile: ./Api/Dockerfile
    networks:
      - backend
    ports:
      - "8000:8080"
    restart: always


volumes:
  pgdata:

networks:
  backend:
    driver: bridge